"""Added new columns is_deleted and modified_by

Revision ID: 8bed8ac00d9f
Revises: ccfdf3d1c556
Create Date: 2025-06-30 01:11:06.957864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bed8ac00d9f'
down_revision: Union[str, Sequence[str], None] = 'ccfdf3d1c556'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('tasks', sa.Column('modified_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'users', ['modified_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'modified_by')
    op.drop_column('tasks', 'is_deleted')
    # ### end Alembic commands ###
