"""Add foreign key to users table

Revision ID: ccfdf3d1c556
Revises: 139eab48dd9a
Create Date: 2025-06-30 00:35:22.086679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccfdf3d1c556'
down_revision: Union[str, Sequence[str], None] = '139eab48dd9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'tasks', 'users', ['assigned_to'], ['id'])
    op.create_foreign_key(None, 'tasks', 'users', ['assigned_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    # ### end Alembic commands ###
