"""modify user table with employee id

Revision ID: e82f1e15c2b2
Revises: a45d4efa4f54
Create Date: 2025-06-25 21:11:01.344951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e82f1e15c2b2'
down_revision: Union[str, Sequence[str], None] = 'a45d4efa4f54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('employee_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'users', ['employee_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'employee_id')
    # ### end Alembic commands ###
